namespace: mysql

replicas: 2
image:
  repo: mysql
  tag: "8.0"
port: 3306

secrets:
  MYSQL_ROOT_PASSWORD: '1234'
  MYSQL_USER: app_user
  MYSQL_PASSWORD: '1234'

resources:
  requests:
    cpu: 500m
    memory: 1Gi
    storage: 2Gi
  limits:
    cpu: 500m
    memory: 1Gi