name: helm-upgrade
run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: 'Environment to deploy to'
        type: string
      version:
        required: true
        type: string
      helm-values-path:
        type: string
        default: './todoapp/values.yaml'
      helm-release-name:
        default: todoapp
        type: string
jobs:
    deploy-helm:
      name: ${{ inputs.environment }}
      runs-on: ubuntu-latest
      environment: ${{ inputs.environment }}

      steps:
      - uses: actions/download-artifact@v4
        with:
          name: helm-package
          path: .

      - uses: actions/download-artifact@v4
        with:
          name: helm-artifacts
          path: .

      - uses: actions/download-artifact@v4
        with:
          name: kind-cluster
          path: .

      - name: Set Up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v4

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          config: ./cluster.yaml

    #   - uses: azure/login@v2
    #     with:
    #       creds: ${{ secrets.AZURE_CREDENTIALS }}

    #   - uses: azure/aks-set-context@v3
    #     with:
    #       resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
        #   cluster-name: ${{ vars.AZURE_CLUSTER_NAME }}

    #   - name: Deploy helm to Development
    #     run: |
    #       helm upgrade --install --atomic --wait --timeout 3600s --debug ${{ inputs.helm-release-name }} ./kube2py-*.tgz \
    #       -f ${{ inputs.helm-values-path }} \
    #       --set mysql.configs.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
    #       --set mysql.configs.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
    #       --set mysql.configs.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
    #       --set todoapp.secrets.SECRET_KEY="${{ secrets.APP_SECRET_KEY }}" \
    #       --set todoapp.secrets.DB_NAME="${{ secrets.APP_DB_NAME }}" \
    #       --set todoapp.secrets.DB_USER="${{ secrets.MYSQL_USER }}" \
    #       --set todoapp.secrets.DB_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
    #       --set todoapp.secrets.DB_HOST="${{ secrets.APP_DB_HOST }}" \
    #       --set todoapp.image.tag=${{ github.sha }}
